import * as GeneralLogo from "../../assets/logo.png";
import * as LivescoreBet from "../../assets/livescore-bet.png";
import * as VirginBetLogo from "../../assets/virginbet-logo.png";
import * as Livescore from "../../assets/livescore.png";

export type AppThemeVars = {
  var: string;
  value: string;
};

export type AppThemeOptions = {
  vars: AppThemeVars[];
  default: boolean;
  name: string;
  siteID: string | number;
  logo: string;
  logoClient: string;
  theme: string;
};

export const Themes: AppThemeOptions[] = [
  {
    default: true,
    name: "Default Theme",
    siteID: "",
    theme: "mock",
    vars: [
      { var: "base-color", value: "#e10a0a" },
      { var: "base-color-700", value: "#c10707" },
      { var: "base-bg-color", value: "#f4f4f4" },
      { var: "global-padding", value: "0px 10px" },
      { var: "global-padding-left", value: "10px" },
      { var: "global-padding-right", value: "10px" },
      { var: "global-border-radius", value: "5px" },
      { var: "global-game-width", value: "450px" },
      { var: "header-border-radius", value: "5px" },
      { var: "league-table-header-color", value: "#8c8c8c" },
      { var: "league-table-body-color", value: "#292b38" },
      { var: "grey-700", value: "#292b38" },
      { var: "bet-buttons-height", value: "42px" },
    ],
    logo: "",
    logoClient: "",
  },
  {
    default: false,
    name: "Virgin",
    siteID: "VRG",
    theme: "virgin",
    vars: [
      { var: "base-color", value: "#e10a0a" },
      { var: "base-color-700", value: "#c10707" },
      { var: "global-padding", value: "0px 10px" },
      { var: "global-padding-left", value: "10px" },
      { var: "global-padding-right", value: "10px" },
      { var: "global-border-radius", value: "5px" },
      { var: "global-game-width", value: "450px" },
      { var: "header-border-radius", value: "5px" },
      { var: "league-table-header-color", value: "#8c8c8c" },
      { var: "league-table-body-color", value: "#292b38" },
      { var: "grey-700", value: "#292b38" },
      { var: "bet-buttons-height", value: "42px" },
      { var: "topbar-bg-color", value: "#e10a0a" },
    ],
    logo: GeneralLogo.default,
    logoClient: VirginBetLogo.default,
  },
  {
    default: false,
    name: "LiveScore Bet",
    siteID: "MOCK",
    theme: "livescore-bet",
    vars: [
      { var: "base-color", value: "#f85b00" },
      { var: "base-color-700", value: "#d65002" },
      { var: "base-bg-color", value: "#121212" },
      { var: "global-padding", value: "0px 10px" },
      { var: "global-padding-left", value: "10px" },
      { var: "global-padding-right", value: "10px" },
      { var: "global-border-radius", value: "5px" },
      { var: "global-game-width", value: "450px" },
      { var: "header-border-radius", value: "5px" },
      { var: "league-table-header-color", value: "#fff" },
      { var: "league-table-body-color", value: "#fff" },
      { var: "grey-700", value: "#292b38" },
      { var: "bet-buttons-height", value: "42px" },
      { var: "loading-text-color", value: "#fff" },
      { var: "game-screen-bg-color", value: "rgba(26, 26, 26, 0.95)" },
      { var: "topbar-bg-color", value: "#2b2b2b" },
      { var: "footer-bg-color", value: "#2b2b2b" },
      { var: "footer-border", value: "#444" },
      { var: "topinfo-text-color", value: "#f85b00" },
      { var: "odds-btn-bgcolor", value: "#333" },
      { var: "odds-btn-border", value: "#555" },
      { var: "odds-btn-textcolor", value: "#fff" },
      { var: "league-table-body-border", value: "1px solid #333" },
      { var: "league-table-header-bgcolor", value: "#2b2b2b" },
      { var: "team-textcolor", value: "#fff" },
      { var: "match-fixture-bgcolor", value: "rgba(26, 26, 26, 1)" },
      { var: "bet-type-btn-border", value: "1px solid #555" },
      { var: "bet-type-btn-bgcolor", value: "#222" },
      { var: "stake-btn-border", value: "1px solid #555" },
      { var: "stake-btn-bgcolor", value: "#333" },
      { var: "stake-input-textcolor", value: "#fff" },
      { var: "overlay-bgcolor", value: "rgba(26, 26, 26, 0.95)" },
      { var: "result-item-bgcolor", value: "#2b2b2b" },
      { var: "result-item-border", value: "1px solid #e64e02" },
      { var: "result-round-name-textcolor", value: "#fff" },
      { var: "knockout-round-title-bgcolor", value: "#2b2b2b" },
      { var: "knockout-results-table-textcolor", value: "#fff" },
      { var: "knockout-results-table-border", value: "1px solid #333" },
      { var: "match-fixture-border", value: "1px solid #333" },
      { var: "mainscore-textcolor", value: "#fff" },
      { var: "knockout-round-title-textcolor", value: "#fff" },
      { var: "knockout-round-title-border", value: "1px solid #333" },
      { var: "overlay-textcolor", value: "#fff" },
      { var: "outright-content-bgcolor", value: "rgba(26, 26, 26, 0.95)" },
      { var: "match-fixture-ptop", value: "5px" },
      { var: "match-fixture-pbottom", value: "5px" },
      { var: "bet-history-textcolor", value: "#fff" },
      { var: "app-game-name-textcolor", value: "#fff" },
      { var: "outright-bet-textcolor", value: "fff" },
    ],
    logo: GeneralLogo.default,
    logoClient: LivescoreBet.default,
  },
  {
    default: false,
    name: "LiveScore Bet",
    siteID: "MOCK",
    theme: "livescore",
    vars: [
      { var: "base-color", value: "#f85b00" },
      { var: "base-color-700", value: "#d65002" },
      { var: "base-bg-color", value: "#fff" },
      { var: "global-padding", value: "0px 10px" },
      { var: "global-padding-left", value: "10px" },
      { var: "global-padding-right", value: "10px" },
      { var: "global-border-radius", value: "5px" },
      { var: "global-game-width", value: "450px" },
      { var: "header-border-radius", value: "5px" },
      { var: "league-table-header-color", value: "#fff" },
      { var: "league-table-body-color", value: "#fff" },
      { var: "grey-700", value: "#292b38" },
      { var: "bet-buttons-height", value: "42px" },
      { var: "loading-text-color", value: "#fff" },
      { var: "game-screen-bg-color", value: "rgba(26, 26, 26, 0.95)" },
      { var: "topbar-bg-color", value: "#2b2b2b" },
      { var: "footer-bg-color", value: "#2b2b2b" },
      { var: "footer-border", value: "#444" },
      { var: "topinfo-text-color", value: "#f85b00" },
      { var: "odds-btn-bgcolor", value: "#333" },
      { var: "odds-btn-border", value: "#555" },
      { var: "odds-btn-textcolor", value: "#fff" },
      { var: "league-table-body-border", value: "1px solid #333" },
      { var: "league-table-header-bgcolor", value: "#2b2b2b" },
      { var: "team-textcolor", value: "#fff" },
      { var: "match-fixture-bgcolor", value: "rgba(26, 26, 26, 1)" },
      { var: "bet-type-btn-border", value: "1px solid #555" },
      { var: "bet-type-btn-bgcolor", value: "#222" },
      { var: "stake-btn-border", value: "1px solid #555" },
      { var: "stake-btn-bgcolor", value: "#333" },
      { var: "stake-input-textcolor", value: "#fff" },
      { var: "overlay-bgcolor", value: "rgba(26, 26, 26, 0.95)" },
      { var: "result-item-bgcolor", value: "#2b2b2b" },
      { var: "result-item-border", value: "1px solid #e64e02" },
      { var: "result-round-name-textcolor", value: "#fff" },
      { var: "knockout-round-title-bgcolor", value: "#2b2b2b" },
      { var: "knockout-results-table-textcolor", value: "#fff" },
      { var: "knockout-results-table-border", value: "1px solid #333" },
      { var: "match-fixture-border", value: "1px solid #333" },
      { var: "mainscore-textcolor", value: "#fff" },
      { var: "knockout-round-title-textcolor", value: "#fff" },
      { var: "knockout-round-title-border", value: "1px solid #333" },
      { var: "overlay-textcolor", value: "#fff" },
      { var: "outright-content-bgcolor", value: "rgba(26, 26, 26, 0.95)" },
      { var: "loadingscreen-bgcolor", value: "rgba(26, 26, 26, 0.95)" },
      { var: "match-fixture-ptop", value: "5px" },
      { var: "match-fixture-pbottom", value: "5px" },
      { var: "bet-history-bgcolor", value: "rgba(26, 26, 26, 0.95)" },
      { var: "bet-history-textcolor", value: "#fff" },
      { var: "app-game-name-textcolor", value: "#fff" },
      { var: "outright-bet-textcolor", value: "fff" },
    ],
    logo: GeneralLogo.default,
    logoClient: Livescore.default,
  },
];
